services:
  redis:
    image: redis:7-alpine
    container_name: unitech-redis
    ports:
      - "6379:6379"
    networks:
      - unitech-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: unitech-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - unitech-network

  eureka-server:
    build: ./eureka-server
    container_name: unitech-eureka
    ports:
      - "8761:8761"
    networks:
      - unitech-network

  ms-auth:
    build: ./ms-auth
    container_name: unitech-auth
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/unitech_auth
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://user:password@unitech-eureka:8761/eureka/
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - rabbitmq
      - eureka-server
    networks:
      - unitech-network

  ms-account:
    build: ./ms-account
    container_name: unitech-account
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/unitech_account
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://unitech-eureka:8761/eureka/
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
      - eureka-server
    networks:
      - unitech-network

  ms-transfer:
    build: ./ms-transfer
    container_name: unitech-transfer
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/unitech_transfer
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://user:password@unitech-eureka:8761/eureka/
    ports:
      - "8083:8083"
    depends_on:
      - rabbitmq
      - eureka-server
    networks:
      - unitech-network

  ms-currency:
    build: ./ms-currency
    container_name: unitech-currency
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://user:password@unitech-eureka:8761/eureka/
    ports:
      - "8084:8084"
    depends_on:
      - redis
      - eureka-server
    networks:
      - unitech-network

  ms-bff:
    build: ./ms-bff
    container_name: unitech-bff
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://user:password@unitech-eureka:8761/eureka/
    ports:
      - "8085:8085"
    depends_on:
      - redis
      - eureka-server
    networks:
      - unitech-network

  api-gateway:
    build: ./api-gateway
    container_name: unitech-gateway
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://user:password@unitech-eureka:8761/eureka/
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - eureka-server
    networks:
      - unitech-network

networks:
  unitech-network:
    driver: bridge